package.json

* Update MathJax dependency to v2.5
* Update info of organization

Update for #64

---

lib/mj-page.js
lib/mj-single.js

Resolves issues #85, #66, and #82

Compensate for removed MathEvents.js.  

---

README.md

add minimal example to Readme

---

package.json

Fix: license information should be spdx coformant

---

package.json

* Change package name to lower case (cf https://docs.npmjs.com/files/package.json)
* Update version to 0.4
* Fix dependencies to major version
* Fix #105 license name must be spdx conformant (#106 was insufficient)

Update package.json for v0.4 release

---

README.md
batik/README.md
bin/page2mml
bin/page2png
bin/page2svg
lib/mj-page.js
lib/mj-single.js
package.json

Merge develop into master

---

lib/patch/jsdom.js

This should fix the problem with travis running node4 tests.  (My fault for not going back to node4 to check the patch properly).

Fix file check to work with node4.

---

lib/mj-page.js
lib/mj-single.js
package.json

* Update MathJax dependency to point to npm
* update libs to match this change
* Clean up dependecy versions
Fixes #159

Update package.json to MathJax from npm

---

bin/am2html
bin/am2htmlcss
bin/mml2html
bin/mml2htmlcss
bin/mml2mml
bin/page2html
bin/tex2htmlcss
lib/mj-page.js
lib/mj-single.js

* Add ability to set the URL for CHTML web fonts (and make the default be the CDN).
* Add command line tools for AsciiMath and MathML to HTML.
* Fix up some comments

More CHTML support.

---

package.json

package.json: update version for release candidate

---

package.json

package.json: point "main" to mj-single

---

lib/mj-page.js
lib/mj-single.js
package.json

This is now the actual PR for the new stree integration.

Semantic Tree Output

---

lib/mj-single.js

[mj-single] add speech to CommonHTML output

---

lib/mj-page.js
lib/mj-single.js

SVG+SRE: change role from math to img

---

lib/mj-single.js
test/issue215.js

[mj-single] HTML output: remove MathJax ids and element frame

---

lib/patch/jsdom.js
test/issue220.js

[CommonHTML] enable displayAlign:"left"

---

lib/mj-single.js

[mj-single] [CommonHTML] reset internal IDs after processing

---

lib/mj-single.js
test/issue241.js

[mj-single] SVG output: add xlink to href in <image>

---

lib/mj-single.js
test/issue236.js

fix speakText + original alttext leading to duplication in output

---

lib/main.js
test/issue260.js

* move state handling from TypesetDone to ReturnResult
Fixes #260

[main] getSVG should increment state.ID

---

lib/main.js
test/base-mathjax.js

[main] pass input data to result object

---

lib/main.js
test/sre-semantictree.js

* add string conversion for xml output of semantic tree. Fixes issue #248
* add test for GetSemantic

[main] GetSemantic: add string conversion

---

lib/main.js

This depends on MathJax v2.7.0.
Fixes #212

[main] simplify MathJaxPath

---

lib/main.js
test/issue219.js

[main] add option for returning dom objects

---

lib/main.js
test/issue277.js

[main] mmlNode should force mml

---

README.md

documentation for deprecated features

---

lib/main.js
test/issue207.js
test/issue289.js

[main.js] getHTML: add aria-label to correct childnode

---

README.md

Includes linting.
Resolves #298

[README] add documentation section

---

README.md

document result.errors, result.height, result.width
Fixes #310

[readme] add documentation

---

README.md
lib/main.js
test/base-config-fonturl.js

Update fontURL, support for reconfiguration

---

lib/main.js
test/userconfig-jax.js

sanitize user configuration

---

.travis.yml

[travis] add nodejs v7

---

lib/main.js
test/issue223.js
test/output-html-linebreaks-manual.js

[main] HTML output: fix manual line-breaks

---

package-lock.json
package.json

* update package version
* update jsdom dependency
* add lock file
Resolves #341

[package] prep v1.1.1 release

---

.travis.yml

[travis] update encrypted deploy key

---

README.md

[readme] document Promise API

---

.travis.yml

[travis] add node 8, 9 to list

---

README.md
package.json

Forgot to change target branch, so this pulls the documentation changes into develop.

Update README and bump version

---

README.md
lib/main.js
package-lock.json
test/assets/test.js
test/config-third-party-extensions.js

* add top-level config option
* add test (inclu. test extension)
* update readme
Resolves #134

[main] add option for custom path variables

---

test/issue219.js

Fix output of issue219 test to correspond to actual test being made.

Fix test issue219

---

lib/main.js
test/base-01-errors-startup.js
test/base-config-extensions.js
test/base-errors-startup.js

 [main] extensions options: support names containing "s"

---

.travis.yml
package-lock.json
package.json

Update lodash as per GitHub warnings.

Update lodash to avoid github warnings

---

.travis.yml
package-lock.json
package.json

This synchronizes develop with master, so that the various package updates that have been done in the different branches are merged, and gets the update travis file.

Sync with master
