lib/mj-page.js, lib/mj-single.js
This makes it easier to use on operating systems (Windows) where /tmp
normally does not exist (and is probably the right thing to do anyhow).
=> Use OS temp directory os.tmpdir() rather than hard-coded /tmp

lib/mj-page.js, lib/mj-single.js
In addition to being more secure, execFile (with arguments as an array)
should work on all platforms because it does not require a hardcoded
quote character. (On windows, quoting with the single ' causes this
call to fail.)
=> Changed Batik calls to use execFile instead of exec

bin/am2mml, bin/am2png, bin/am2svg, bin/mml2mml, bin/mml2png, bin/mml2svg, bin/mml2svg-html5, bin/page2mml, bin/page2png, bin/page2svg, bin/tex2mml, bin/tex2png, bin/tex2svg, bin/tex2svg-filter, lib/mj-page.js, lib/mj-single.js
Adds an 'extensions' option to config which takes a comma-separated
list of extensions to add to the default set. Then adds --extensions
parameter to each command-line tool to specify this value.
This allows use of MathJax features such as displaying invalid TeX
instead of failing to render (--extensions TeX/noUndefined), and
stripping out dangerous links from MathML (--extensions Safe).
=> Allow extensions to be specified on command line

README.md, batik/README.md, bin/am2mml, bin/am2png, bin/am2svg, bin/mml2mml, bin/mml2png, bin/mml2svg, bin/mml2svg-html5, bin/page2mml, bin/page2png, bin/page2svg, bin/tex2mml, bin/tex2png, bin/tex2svg, bin/tex2svg-filter, lib/mj-page.js, lib/mj-single.js, package.json
Are we good to go? E.g., #64 seems fixed now.
Also fixes #85, #82, #70, #62, #31
=> Release 0.3

lib/mj-page.js, lib/mj-single.js, package.json
Updates jsdom to enable upcoming node+iojs merge (v4). 
:warning:  This drops compatibility for older nodejs versions.
Closes #110.
=> update jsdom for iojs / nodejs v4 compatibility

lib/mj-page.js, lib/mj-single.js
When you have more than 1 request hitting the server at the exact same time, they both try to access the same hard coded filename. This just adds the process id to the filename so the concurrent requests don't try to use the same temp file.
=> adding process id to tmp file to allow for concurrency

lib/patch/jsdom.js
This should allow the jsdom patch to work in either node4 or node5 hierarchy.
=> Handle jsdom update in either node4 or node5 directory layout

lib/patch/jsdom.js
This makes setting individual margin or padding sides also update the general margin or padding style.
=> Add more patches for padding and margin

README.md
Just for user convenience, really.
=> Made the first mention of Mathjax a link

lib/patch/jsdom.js
The current test was dependent on the current directory.  My tests were done from the mathjax-node directory itself, but when it is installed with `npm install mathjax-node`, rather than getting a copy of mathjax-node from github and running `npm install` in it, you get a `node_modules` directory, and so the current directory is not the same as what I was using, and the test for node version 4 failed, and it tried to use the node-5 hierarchy.  This leads to the error reported in issues #172 and #179.
This patch uses a test that doesn't rely on the current directory.
=> Make test for node hierarchy more robust.

README.md, lib/patch/jsdom.js, package.json
A very small bugfix release.
#182 Improve patch for older jsdom versions. Resolves issues #172 and #179.
=> Merge develop into master for v0.5.1 release

bin/page2html, lib/mj-page.js, test/issue181-1.js, test/issue181-2.js
Don't include a style in the output when there isn't any math on the page, and remove an old copy of the styles if there was one already, and add some comments about what is going on.
Resolves issue #181
=> Don't include a style in the output when there isn't any math on the page

bin/tex2stree, lib/mj-single.js
Exposes the semantic tree via MathJax-node.
I included the stree computations into the general pipeline. I still feel this is overkill if one wants to only translate TeX into a MML/Stree.
I admit that I have no clue what ConfigureMathJax and StartQueue really do and I would strongly argue for their refactoring into smaller reusable/composable methods.
=> Adds semantic tree output mj-single and a demonstrator executable.

bin/am2stree, bin/mml2stree, bin/tex2stree
Adds the scripts to translate MathML and AsciiMath to semantic tree.
Further to our previous conversation: I really believe we should have a single binary with tons of options here, because I feel this is what people will (want to) use, instead of writing their own little wrappers.
=> Complete sre scripts

lib/mj-single.js
This resolves the problem of having delimiters as part of the math passed to mj-single, and also prevents the need for the preprocessors.
[Fixes #226]
=> Use <script> tags rather than delimited math in mj-single.

lib/patch/jsdom.js
This patches the copy of CSSStyleDeclaration to handle units of `ex` and a number of other missing units.  The change really should only be in one line (the `lengthRegEx`), but since that is down inside a closure, I can't get my hands on it, so I have to replace the entire `valueType()` routine with a duplicate that uses my own copy of `lengthRegEx`.  Resolves issue #233.
=> Patch CSSStyleDeclaration to handle units of 'ex' (and others).  Resolves issue #233

lib/patch/jsdom.js
Make sure padding and margin can accept 0 to mean 0px.  Resolves issue #244
=> Make sure padding and margin can accept 0 to mean 0px.  #244

lib/main.js, lib/patch/jsdom.js, package.json
Fix jsdom patch to work with version 9 as well as version 7, and set user agent since the one in version 9 now makes MathJax think it is Safari.  Resolves issue #266.
=> Fix jsdom patch to work with version 9.  #266

lib/main.js, test/issue175.js
=> Prevent the color extension from auto-loading

lib/main.js, test/issue276.js
This defines the `pxPerInch` value needed for absolute units like `cm`, `mm`, `in`, etc. that is usually computed by measuring DOM elements.  Resolves #275.
=> Add missing pxPerInch value.  #275

lib/main.js, test/issue277.js
Don't produce `mml` when `mmlNode` is produced (unless `mml` is also requested).  Fixes a problem with PR #282, and resolves #277.
=> Don't produce mml when mmlNode is requested if mml wasn't requested. #277

lib/main.js, test/issue288.js
=> [main.js] add missing checks for htmlNode

lib/main.js, test/css.js
=> [main] enable css output without html output

lib/main.js, test/pass_data.js
=> [main] improve passing of input data to output

lib/main.js, test/mathjax-config-combined.js
Remove `config` array to avoid errors from e.g. loading combined configurations
Fixes #330
=> [main] config: sanitize MathJax configuration

lib/main.js, test/base-typeset-promise.js, test/base-warnings.js
=> [main] typeset: add promise-based API

lib/main.js
=> Use new None output for mml-only output

README.md, package.json
Update README and bump version (so we can tag a release and get `npmjs` readme updated).
Resolves issue #383.
=> Update README and bump version.  #383

lib/main.js, test/useFontCache.js
Define the None output jax after the other jax are loaded (so SVG will be loaded initially, so its configuration can be set by hand).  Resolves issue #392.
=> Define the None output jax after the other jax are loaded

test/base-typeset-promise.js, test/base-warnings.js, test/issue175.js, test/svg-full-width-chars.js
This makes the output of running the test suite easier read.  (I also like to pipe it though tap-spec to prettify it even more.)
=> Suppress unwanted error output in tests

lib/main.js, test/base-config-fonturl.js, test/base-mathjax.js, test/base-typeset-promise.js, test/base-warnings.js, test/config-third-party-extensions.js, test/css.js, test/issue104.js, test/issue175.js, test/issue207.js, test/issue215.js, test/issue219.js, test/issue220.js, test/issue223.js, test/issue241.js, test/issue260.js, test/issue276.js, test/issue277.js, test/issue288.js, test/issue289.js, test/mathjax-config-combined.js, test/output-html-linebreaks-manual.js, test/pass_data.js, test/svg-full-width-chars.js, test/svg-metadata.js, test/useFontCache.js, test/userconfig-autoload.js, test/userconfig-jax.js
If `start()` was called while MathJax was starting up from a previous `start()` or `typeset()` call, this could cause crashes (and did cause crashes for some tape tests). 
This PR fixes `start()` so that it delays the restart until the previous MathJax has started up.
It also removes unneeded `start()` calls from the test files (no need to create a new window and reload MathJax unnecessarily), and adds configuration resets for those tests that include configuration changes.  Finally, it normalizes the format of the tests.
=> Fix start() to handle being called while MathJax is starting up
